server:
  port: 9003
  
spring:
  application:
    name: zuul-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/

zuul:
  #Service will be mapped under the /api URI
  prefix: /api
#  Uncomment to disable auto-registering all services read from Eureka
#  ignoredServices: '*'
#  use url attribute to use service URL instead of serviceId
  routes:
    PRODUCTS-CRAWLER:
      path: /crawler-service/**
      serviceId: PRODUCTS-CRAWLER
    PRODUCTS-DB:
      path: /prducts-db-service/**
      serviceId: PRODUCTS-DB

